name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5

      - parallel:
          - name: Typecheck
            run: deno check
          - name: Format check
            run: deno fmt --check
          - name: Lint
            run: deno lint

  test:
    name: Install Zig test
    needs: check
    strategy:
      fail-fast: false
      # https://github.com/actions/runner-images#available-images
      matrix:
        os:
          - ubuntu-26.04
          - ubuntu-26.04-arm
          - ubuntu-slim
          - xcode-27
          - macos-26-intel
          - windows-2025
          - windows-11-vs2026-arm
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Zig
        uses: ./
        with:
          version: latest
          cache: false

      - name: Verify Zig
        run: |
          zig version
          zig env
